# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LocatePlleXY
                                 A QGIS plugin
 Plugin de recherche et localisation par coordonnées XY ou identifiant parcellaire (Nature, Numéro, Indice)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-23
        copyright            : (C) 2025 by California29
        email                : gabrieltorue@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LocatePlleXY class from file LocatePlleXY.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .LocatePlleXY import LocatePlleXY
    return LocatePlleXY(iface)
